# This file was generated by GoReleaser. DO NOT EDIT.
cask "smrte" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5ce76f831b4b67fecf29804ff33a634a7a12c78f506d963ae8795b62788f300c"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
    on_arm do
      sha256 "883182591fe7d36a1cca2eb85dd1caebe02c0ac311fce9c16c0072d932592656"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "9371465aa5b12054d5eef404f97aca47050f8a2ae29a9e9d8e8885de342a8dfc"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_linux_amd64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
    on_arm do
      sha256 "bdb0f5122ab4c6822c8266dad71f4b77c677e10ab4f71592591940dac1937c3d"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_linux_arm64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
  end

  name "smrte"
  desc "Cross-platform CLI for the smrt-E API"
  homepage "https://smrte.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smrte"

  # No zap stanza required

end
