# This file was generated by GoReleaser. DO NOT EDIT.
cask "smrte" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "13112386c0ab198de161ea0c876e55bff36b378a2c66b38efe5df28cf7dae0f8"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
    on_arm do
      sha256 "d92dec182c36ccb6f998b9654773cdb0330e01770aea7a240690a7ed039d3409"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "69012fac7caa87af201df9fcde4485d71d0aaf8ddf9a2b1a1de01a5f346c22ad"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_linux_amd64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
    on_arm do
      sha256 "168150778b404a22e6027002fa14ed2edd56233098c26d45df772269121432d9"
      url "https://github.com/smartbuild-construction-solutions/smrte-cli/releases/download/v#{version}/smrte_#{version}_linux_arm64.tar.gz",
        verified: "github.com/smartbuild-construction-solutions/smrte-cli"
    end
  end

  name "smrte"
  desc "Cross-platform CLI for the smrt-E API"
  homepage "https://smrte.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smrte"

  # No zap stanza required

end
