# This file was generated by GoReleaser. DO NOT EDIT.
cask "smrte" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "049d09d79ee9d3eb507b48f5757cfc9225405565e265147537f0af462c44ace8"
      url "https://github.com/smartbuild-construction-solutions/homebrew-tap/releases/download/smrte-cli-v#{version}/smrte_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "940cbe5e3b9dc113945185e5e3ef0c0aa5ca55e0481f65af0b01b2e100aa1364"
      url "https://github.com/smartbuild-construction-solutions/homebrew-tap/releases/download/smrte-cli-v#{version}/smrte_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3421ca5d29b80ffec49ed6a7f544d7a7e32aaa88f9a5cee6304f39a2a3097483"
      url "https://github.com/smartbuild-construction-solutions/homebrew-tap/releases/download/smrte-cli-v#{version}/smrte_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "366ae271f3a7758546c9de68a5a35acbc4b014af25c253058e170ff9051bcf02"
      url "https://github.com/smartbuild-construction-solutions/homebrew-tap/releases/download/smrte-cli-v#{version}/smrte_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smrte"
  desc "Cross-platform CLI for the smrt-E API"
  homepage "https://smrte.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smrte"

  # No zap stanza required
end
